[package]
name = "revenq"
description = "A concurrent, revision-based event queue implementation"
version = "0.0.0"
authors = ["Erik Zscheile <zseri.devel@ytrizja.de>"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/YZITE/revenq"

[dependencies]
atom = "0.3"
triomphe = "0.1"
