[package]
name = "revenq"
description = "A concurrent, revision-based event queue implementation"
version = "0.0.4"
authors = ["Erik Zscheile <zseri.devel@ytrizja.de>"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/YZITE/revenq"
readme = "README.md"
exclude = ["/.github/", "Cargo.toml"]

[package.metadata.docs.rs]
all-features = true

[features]
default = ["woke-queue"]
woke-queue = ["async-task", "crossbeam-utils", "futures-core", "pin-utils"]

[dependencies]
async-task = { version = "2.1", optional = true }
cfg-if = "0.1"
crossbeam-utils = { version = "0.7", optional = true }
futures-core = { version = "0.3", optional = true }
pin-utils = { version = "0.1.0-alpha.4", optional = true }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "queue"
harness = false

[[example]]
name = "woke_queue"
required-features = ["woke-queue"]

[[test]]
name = "woke_queue"
required-features = ["woke-queue"]
