[package]
name = "revenq"
description = "A concurrent, revision-based event queue implementation"
version = "0.0.5"
authors = ["Erik Zscheile <zseri.devel@ytrizja.de>"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/reclutch-nursery/revenq"
readme = "README.md"
exclude = ["/.github/", "Cargo.toml"]

[dependencies]
event-listener = "2.2"
futures-lite = "0.1"

[dependencies.stable_deref_trait]
version = "1"
default-features = false
optional = true

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "queue"
harness = false

[[example]]
name = "queue"
